spring:
  datasource:
    url: jdbc:mysql://localhost:3307/salescloud_customer?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none



